### ISSUE TITLE
Convert Gif Files To Flipnote Animations...

### ISSUE THREAD

**Issue by RunTheCoins** [jaames/flipnote-player#17]
Back Last Year I Tried To Figured Out How To Play A Gif File On Flipnote, And It Never Worked... It Would Be REALLY Cool If You Can Have A Two Way Conversion On Your Site, I Think It Would Open Up New Possibilitys For Flipnote Studio In General... So If You Can Figure It Out, Please Add It To Your Site!

**Comment by jaames** [comment]
not something that would be possible due to lack of metadata from the gif, and im not really interested in encoding flipnotes anyway for a variety of reasons
