### ISSUE TITLE
Audio on exported MP4s is out of sync

### ISSUE THREAD

**Issue by wastelandpikachu** [jaames/flipnote-player#24]
On the exported MP4s the audio is about a half-second ahead of the video. The first frame is held for a bit too long. This problem isn't present in the Flipnote Player.

**Comment by jaames** [comment]
please provide more details; I'm pretty certain it is not out of synch

**Comment by wastelandpikachu** [comment]
Sorry I posted it without a description. I will attach videos of the player and converted flipnote.

**Comment by wastelandpikachu** [comment]
Actually it's a problem with the Windows Media Player. Nevermind
