### ISSUE TITLE
Background of canvas does not match white paper in dark mode

### ISSUE THREAD

**Issue by thejsa** [jaames/flipnote-player#8]
![image](https://user-images.githubusercontent.com/10799473/46393411-18be5900-c6dd-11e8-9612-0b31087b19dc.png)
Presumably this could be fixed by adjusting the background of the canvas to match the paper colour - I'll take a look at this when I get home today.

**Comment by jaames** [comment]
Hey thanks for the report! That's... certainly odd. I haven't experienced this before.

A few things that would help diagnose the issue:
- What OS / browser / GPU was this on?
- Is it behaving like the canvas is totally transparent? That is, if you change the background colour of the element behind it, can you see that colour through the canvas? 
- Is this the only sample Flipnote affected?
- Any errors in the devtools console and/or network tab?

**Comment by jaames** [comment]
Also forgot to mention this is technically a [flipnote.js](https://github.com/jaames/flipnote.js) issue.

You can see the default options being passed to getContext [here](https://github.com/jaames/flipnote.js) -- maybe this needs `alpha:false`? Otherwise I expect it might be some weird browser thing with the call to clearColor [here](https://github.com/jaames/flipnote.js/blob/master/src/webgl/canvas.js#L139)

**Comment by thejsa** [comment]
>     * What OS / browser / GPU was this on?
Debian 9; Mozilla Firefox ESR 60; Intel HD Graphics
>     * Is it behaving like the canvas is totally transparent? That is, if you change the background colour of the element behind it, can you see that colour through the canvas?
Seems so!
>     * Is this the only sample Flipnote affected?
No, all are
>     * Any errors in the devtools console and/or network tab?
Unable to check this at the moment, but I can later.

**Comment by jaames** [comment]
Thanks, I think I found the issue! 

Firstly, `setPaperColor` was expecting colors to have an alpha channel (they don't), plus the webgl canvas was being created without using `alpha : false` to disable the transparency buffer. 

Just pushed a fix to flipnote.js, so I'll pull that in here and rebuild in a second. :)

**Comment by jaames** [comment]
Should be live now, although I didn't bump the version since it's technically a dependency issue :P
