### ISSUE TITLE
Audio doesnt work on firefox

### ISSUE THREAD

**Issue by redg3ar** [jaames/flipnote-player#9]
This is a lovely project, and I wish you best of luck with the 3ds audio format! Anyway, here is the firefox im using. This also happens for my friend on non nightly firefox on windows.

Name: Firefox
Version: 64.0a1
Build ID: 20180923220427
Update Channel: nightly
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0
OS: Linux 4.19.0-rc7-beppy+

**Comment by redg3ar** [comment]
I somehow only clicked on only 3DS ones throughout my testing :P

**Comment by jaames** [comment]
Oh haha, no worries! Perhaps I could better communicate that 3ds flipnotes don't currently have audio though :P
